AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'spec/support'
    - 'spec/factories'
    - 'spec/fixtures'
    - 'spec/support/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/*'
    - 'app/controllers/users/base_controller.rb'
    - 'app/controllers/users/base_controller.rb'
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/ParallelAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  Max: 130

Style/ClassAndModuleChildren:
  Enabled: false
